# Generated by Django 5.1.2 on 2025-02-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='size',
            field=models.IntegerField(default=10),
        ),
    ]
